django_sh/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sh/', include('sh.urls')),
]

sh/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "sh"

urlpatterns = [
    path('', views.command, name="command"),
    path('command/', views.command, name="command"),
    path('command/<int:pk>/', views.command, name="command"),
    path('settings/', views.editar_configuracion, name="settings"),
    path('reports/', views.reports, name="reports"),
    path('view_report/<int:pk>/', views.view_report, name="view_report"),
    path('command_history/', views.command_history, name="command_history"),
    path('saved_commands/', views.saved_commands, name="saved_commands"),
    path('save_command/<int:pk>/', views.save_command, name="save_command"),
]

urlpatterns = urlpatterns + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

sh/forms.py
import datetime
from django import forms
from django.contrib.auth.models import User
from django.forms.widgets import ClearableFileInput
from . import functions
from .constants import (
    ELEMENTOS_PAGINA,
    MESES,
    SOLO_FECHA_ANTERIOR,
    SOLO_FECHA_POSTERIOR,
    DESDE_1900,
    ANIOS,
)

EMPTY_CHOICE = (("", "---"),)

class BootstrapForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(BootstrapForm, self).__init__(*args, **kwargs)

        for field in self.fields.keys():
            if "class" in self.fields[field].widget.attrs:
                self.fields[field].widget.attrs["class"] += " form-control"
            else:
                self.fields[field].widget.attrs["class"] = "form-control"


class BootstrapModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(BootstrapModelForm, self).__init__(*args, **kwargs)

        for field in self.fields.keys():
            if "class" in self.fields[field].widget.attrs:
                self.fields[field].widget.attrs["class"] += " form-control"
            else:
                self.fields[field].widget.attrs["class"] = "form-control"

class CalendarWidget(forms.DateInput):
    def __init__(self, fecha_validate=0, datetime=False, attrs={'autocomplete':'off'}):

        clases = ""
        if datetime:
            clases = "has_datetimepicker"
            attrs["size"] = "15"
        else:
            clases = "has_datepicker"
            attrs["size"] = "7"

        if fecha_validate == 0:
            clases = "%s fecha_posterior fecha_anterior" % clases

        if fecha_validate == 1:
            clases = "%s fecha_anterior" % clases

        if fecha_validate == 2:
            clases = "%s fecha_posterior" % clases

        attrs["class"] = clases
        super(CalendarWidget, self).__init__(attrs=attrs)


class CalendarDateTimeWidget(forms.DateTimeInput):
    def __init__(
        self, fecha_validate=SOLO_FECHA_ANTERIOR, datetime=True, attrs={}
    ):

        clases = ""
        clases = "has_datetimepicker"
        attrs["size"] = "15"

        if fecha_validate == SOLO_FECHA_ANTERIOR:
            clases = "%s solo_fecha_anterior" % clases

        if fecha_validate == SOLO_FECHA_POSTERIOR:
            clases = "%s solo_fecha_posterior" % clases

        if fecha_validate == DESDE_1900:
            clases = "%s solo_fecha_anterior bigbang" % clases

        attrs["class"] = clases
        super(CalendarDateTimeWidget, self).__init__(attrs=attrs)


class CalendarDateField(forms.DateField):
    def __init__(self, fecha_validate=0, *args, **kwargs):
        calendar_widget = CalendarWidget(
            fecha_validate=fecha_validate, datetime=False
        )

        super(CalendarDateField, self).__init__(
            input_formats=("%d/%m/%y", "%d/%m/%Y"),
            widget=calendar_widget,
            *args,
            **kwargs
        )

class CalendarDateTimeField(forms.DateTimeField):
    def __init__(self, fecha_validate=SOLO_FECHA_ANTERIOR, *args, **kwargs):
        calendar_widget = CalendarDateTimeWidget(
            fecha_validate=fecha_validate, datetime=True
        )
        if "widget" in kwargs:
            calendar_widget = kwargs["widget"]
            del kwargs["widget"]

        super(CalendarDateTimeField, self).__init__(
            input_formats=(
                "%d/%m/%Y %H:%M",
                "%d/%m/%y %H:%M",
                "%d/%m/%y %H:%M:%S",
                "%d/%m/%Y %H:%M:%S",
            ),
            widget=calendar_widget,
            *args,
            **kwargs
        )

class FiltroForm(BootstrapForm):

    SI_NO_OP = (("", "------------"), (1, u"Sí"), (0, u"No"))
    STATUS_OP = (
        ("activos", "Activos"), 
        ("inactivos", "Inactivos"),
        ("todos", "Todos"),
    )
    STATUS_PROVEEDOR = (
        ("","----------------"),
        (1,"En proceso de alta"),
        (2,"Vigente"),
    )
    STATUS_CONTRATO = (
        ("","----------------"),
        (1,"Activo"),
        (2,"Inactivo"),
    )

    page_size = forms.ChoiceField(choices=ELEMENTOS_PAGINA, required=False)

    # req_year = forms.ChoiceField(required=False)
    year = forms.ChoiceField(choices=ANIOS, required=False)

    # req_month = forms.ChoiceField(choices=MESES, required=False)
    month = forms.ChoiceField(choices=MESES, required=False)

    q = forms.CharField(max_length=100, required=False)

    # cuenta_bancaria = forms.ModelChoiceField(CuentaBancaria.objects.none())
    proveedor = forms.CharField(
        required=False, widget=forms.TextInput(attrs={"autocomplete": "off"})
    )
    desde = CalendarDateField(required=False)
    hasta = CalendarDateField(required=False)
    fechahora = CalendarDateTimeField(required=False)
    categoria = forms.CharField(
        required=False, widget=forms.TextInput(attrs={"size": 7})
    )
    subcategoria = forms.CharField(
        required=False, widget=forms.TextInput(attrs={"size": 7})
    )
    subsubcategoria = forms.CharField(
        required=False, widget=forms.TextInput(attrs={"size": 7})
    )
    
    #usuario = forms.ModelChoiceField(
    #    queryset=User.objects.none(), required=False
    #)
    fecha = CalendarDateField(required=False)

    desde_month = forms.ChoiceField(choices=MESES, required=False)
    desde_year = forms.ChoiceField(required=False)
    hasta_month = forms.ChoiceField(choices=MESES, required=False)
    hasta_year = forms.ChoiceField(required=False)

    si_no = forms.ChoiceField(choices=SI_NO_OP, required=False)
    status = forms.ChoiceField(choices=STATUS_OP, required=False)

    booleano = forms.BooleanField(required=False)

    choices = forms.ChoiceField(choices=[], required=False)
    choices2 = forms.ChoiceField(choices=[], required=False)
    choices3 = forms.ChoiceField(choices=[], required=False)
    choices4 = forms.ChoiceField(choices=[], required=False)

    #Reportes
    fecha_vigencia = CalendarDateField(required=False)
    status_contrato = forms.ChoiceField(choices=STATUS_CONTRATO, required=False)
    status_proveedor = forms.ChoiceField(choices=STATUS_PROVEEDOR, required=False)
    fecha_ultima_compra_menor =CalendarDateField(required=False)
    monto_menor_a = forms.CharField(required=False)
    desde_fecha_batch = CalendarDateField(required=False)
    hasta_fecha_batch  = CalendarDateField(required=False)
    
    def clean_q(self):
        """
        Se limpian los espacios extra.
        """
        return " ".join(self.cleaned_data["q"].split())


    def clean(self):
        cleaned_data = self.cleaned_data
        desde = functions.to_datetime(cleaned_data.get("desde"))
        hasta = functions.to_datetime(cleaned_data.get("hasta"), max=True)
        year = cleaned_data.get("year")
        month = cleaned_data.get("month")

        return cleaned_data

    def __init__(self, *args, **kwargs):
        super(FiltroForm, self).__init__(*args, **kwargs)

        """
        #self.fields["cedis"].queryset = get_cedis() 
        self.fields["usuario"].queryset = User.objects.filter(is_active=True)
        
        today = datetime.date.today()
        self.initial["desde"] = today
        self.initial["hasta"] = today
        self.initial["year"] = today.year
        self.initial["month"] = today.month
        self.initial["desde_year"] = today.year
        self.initial["hasta_year"] = today.year
        self.initial["desde_month"] = today.month
        self.initial["hasta_month"] = today.month
        
        if hasattr(self.data, '_mutable') and not self.data._mutable:
            self.data = self.data.copy()

        if self.data.get('month') is None:
            self.data['month'] = today.month
        if self.data.get('year') is None:
            self.data['year'] = today.year  
        if self.data.get('desde') is None:
            self.data['desde'] = today
        if self.data.get('hasta') is None:
            self.data['hasta'] = today
        if self.data.get('activa') is None:
            self.data['activa'] = 1
        """

sh/views.py
from operator import length_hint
from django.contrib.auth.decorators import login_required, permission_required
from django.db import models
from django.shortcuts import get_object_or_404, render, HttpResponse, redirect
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from .models import SavedCommand, ShellSettings, Command
from django.contrib.auth.decorators import user_passes_test
from django.utils import timezone
from django.urls import reverse
from . import utils_views
from .forms import FiltroForm, EMPTY_CHOICE


#@user_passes_test(lambda u: u.is_superuser)
def command(request, pk=None): 
    shell_settings = ShellSettings.objects.get_or_create()[0]
    error = shell_settings.is_valid_request(request)
    if error:
        return HttpResponse(error)
    
    error = ''
    command_obj = None
    objects = []
    matrix = []
    
    if request.method == 'POST':
        command_obj, error = ejecutar(request)  
        return redirect(reverse("sh:command", args=[command_obj.pk]))
    
    default_command_text = ""
    if pk:
        command_obj = get_object_or_404(Command, pk=pk)
        default_command_text = command_obj.text

    command = request.POST.get("query", default_command_text)
    return render(request, 'sh/command.html', { 
        'objects':objects, 
        'query': command, 
        'command_obj': command_obj, 
        'error':error,
        "pk":pk
    }) 


#@user_passes_test(lambda u: u.is_superuser)
def ejecutar(request):
    from builtins import str

    try:
        shell_settings = ShellSettings.objects.get()
    except ObjectDoesNotExist:
        shell_settings = ShellSettings.objects.get_or_create()[0]
       
    command = Command(user=request.user)
    objects = []
    matrix = []
    query = request.POST.get('query', '').strip()
    q = query.replace("\r","")
    q += "\n"
    error = ""

    command.start = timezone.now()
    command_string = ""

    # helpers
    _ = objects.append
    
    command.text = f"{q}"
    command_string += f"{command.text}\n"

    if shell_settings.code_after:
        command_string += f"\n\n{shell_settings.code_after}"

    command.save()

    if request.POST.get("enable_try"):
        try:
            exec(shell_settings.code_before)
            exec(command_string)
        except Exception as e:
            error = u"%s %s" % (str(e.__class__), str(e))
    else:
        exec(shell_settings.code_before)
        exec(command_string)    
    
    command.end = timezone.now()
    out = "\n".join([str(x) for x in objects])
    command.output = f"No. de elementos: {len(objects)} \n {out}"
   

    if error:
        command.error = error

    command.save()

    return command, error

#@user_passes_test(lambda u: u.is_superuser)
def editar_configuracion(request):
    shell_settings = ShellSettings.objects.get_or_create()[0]
    error = shell_settings.is_valid_request(request)
    if error:
        return HttpResponse(error)

    if request.method == "POST":
        shell_settings.code_before = request.POST.get("code_before")
        shell_settings.auth_function = request.POST.get("auth_function")
        shell_settings.save()
        return redirect("sh:command")
    
    return render(
        request,
        'sh/settings.html',
        {"shell_settings":shell_settings},
    )

def reports(request):
    return redirect("/")


#@user_passes_test(lambda u: u.is_superuser)
def save_command(request, pk):
    shell_settings = ShellSettings.objects.get_or_create()[0]
    error = shell_settings.is_valid_request(request)
    if error:
        return HttpResponse(error)

    instance = get_object_or_404(Command, pk=pk)
    saved_command = SavedCommand.objects.create(
        command=instance, 
        user=request.user,
    )
    return redirect("sh:command_history")

@user_passes_test(lambda u: u.is_superuser)
def view_report(request, pk):
    """
    No hace validación de firewall
    """

    if request.user.is_anonymous:
        return redirect("/")

    instance = get_object_or_404(Command, pk=pk)
    
    prohibited_strings = [
        "delete",
        "save",
        "update",
        "create",
    ]
    for ps in prohibited_strings:
        assert not ps in instance.text

    objects = []
    matrix = []
    _ = objects.append
    try:
        exec(shell_settings.code_before)    
        exec(instance.text)
    except Exception as e:
        return HttpResponse(e)
        
    return format_response(matrix)

def format_response(matrix, is_table=True):

    if is_table:
        outtxt = "<table>\n"
        for line in matrix:
            outtxt += "<tr>\n"    
            for col in line:
                outtxt += f"    <td>{col}</td>\n"
            outtxt +="</tr>\n"
        outtxt += "</table>"
    else:
        outtxt = "<br />".join(matrix)

    return HttpResponse(outtxt)  

#@user_passes_test(lambda u: u.is_superuser)
def saved_commands(request):
    rget = request.GET.copy()
    shell_settings = ShellSettings.objects.get_or_create()[0]
    shell_settings.is_valid_request(request)

    rget = request.GET.copy()
    rget["usuario"] = request.user

    filtro_form = FiltroForm(request.GET)

    if filtro_form.is_valid():
        q = filtro_form.cleaned_data["q"]
        desde = filtro_form.cleaned_data["desde"]
        hasta = filtro_form.cleaned_data["hasta"]
        objects = request.user.sh_saved_commands.all()

        if q:
             objects = objects.filter(
                models.Q(command__text__icontains=q)
            )

        if desde:
            objects = objects.filter(
                models.Q(command__start__gte=desde)
            )
        
        if hasta:
            objects = objects.filter(
                models.Q(command__start__lte=hasta)
            )

        return utils_views.list_view(
            request,
            objects,
            template='sh/saved_commands.html',
            variables = {
                'filtro_form':filtro_form,
            }
        
        )


#@user_passes_test(lambda u: u.is_superuser)
def command_history(request):
    shell_settings = ShellSettings.objects.get_or_create()[0]
    shell_settings.is_valid_request(request)

    filtro_form = FiltroForm(request.GET)

    if filtro_form.is_valid():

        objects = Command.get_objects(filtro_form.cleaned_data)

        return utils_views.list_view(
            request,
            objects,
            template='sh/command_history.html',
            variables = {
                'filtro_form':filtro_form,
            }
        
        )

sh/templates/sh/command.html
{% extends 'sh/layout.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'sh/codemirror/lib/codemirror.css' %}">
<link rel="stylesheet" href="{% static 'sh/codemirror/theme/monokai.css' %}">
<link rel="stylesheet" href="{% static 'sh/css/main.css' %}">

<script type="text/javascript" src="{% static 'sh/codemirror/lib/codemirror.js' %}"></script>
<script type="text/javascript" src="{% static 'sh/codemirror/mode/python/python.js' %}"></script>

<style>
    {% if command_obj.error %}
        .error{
            background-color: #bd2626;
            color: #f9f9f9;
            font-size: 17px;
            margin: 10px 0;
            padding: 10px;
            border-radius: 2px;
        }
    {% endif %}
    pre{
        color: white;
        margin: 0;
        padding: 10px 15px;
        max-height: 90vh;
        border-radius: 2px;
        max-width:100%;
        white-space:normal; 
    }
</style>
{% endblock %}



{% block contenido %}
    <div class="row">
        <div class="col-md-7">
            <form method="post" action="." name="myForm">
                {% csrf_token %}
                <div class="row">
                    <div>
                        <label class="control control-checkbox mb-1 mr-2">
                            <input type="checkbox" checked="checked" name="enable_try"> 
                            Habilitar try/catch
                            <span class="control_indicator"></span>
                        </label>
                    </div>
                </div>
                {% if pk %}
                    <div class="row" >
                        <div style="text-align: right;">
                            <a class="btn btn-sm btn-dark mr-2" href="{% url 'sh:save_command' pk %}">Guardar en favoritos</a>

                        </div>
                        <div style="text-align: left;">
                            <b class="pre">Inicio: </b>{{ command_obj.created_at|date:"d/m/Y - H:i" }}|
                            <b class="pre">Fin: </b>{{ command_obj.end|date:"d/m/Y - H:i" }}|
                            <b class="pre">Duracion: </b>{{command_obj.get_duracion }}|
                            <b class="pre">Ejecutado por: </b>{{ command_obj.user.username }}
                        </div>
                    </div>
                {% endif %}

                <textarea name="query" id="id_query" class="query-textarea">{{ query }}</textarea>

                <div class="text-right my-2">
                    <input type="submit" value="Ejecutar" class="btn btn-dark" id="ejecutar">
                </div>
            </form>
        </div>
        <div class="col-md-5">
            <div style="max-height:95vh;overflow:auto"> 
                {% if command_obj.error %}
                <div class="error">{{ command_obj.error }}</div>
                {% endif %}

                <pre>
                    {{ command_obj.output|linebreaks }}
                </pre>
            </div>
        </div>
    </div>

<script>
var h = window.outerHeight;

window.editor = CodeMirror.fromTextArea(document.getElementById("id_query"), {
    mode: {name: "python", singleLineStringErrors: false},
    lineNumbers: true,
    indentUnit: 4,
    matchBrackets: true,
    theme: 'monokai',
    autofocus: true,
    extraKeys: {
        "Tab": function(cm){
          cm.replaceSelection("    " , "end");
        }
    }
});

window.editor.on("keydown", function (cm, event) {
  event = {
    type: "keydown",
    keyCode: event.keyCode,
    ctrlKey: event.ctrlKey,
    shiftKey: event.shiftKey,
    altKey: event.altKey,
    metaKey: event.metaKey
  };
            
  if (event.ctrlKey && event.keyCode == 13) {
    $("#ejecutar").click()
  }
});


window.editor.setSize(null, h - 250);
</script>
{% endblock %}

sh/templates/sh/command_history.html
{% extends 'sh/layout.html' %}
{% load static %}

{% block contenido %}
<div class="row">
    <div class="col-md-12">
        <form method="GET" action=".">
            <div class="aling-bottom d-inline-block">
				<label for="fecha_min">Desde</label>
				 {{ filtro_form.desde }}
				 {{ filtro_form.desde.errors }}
			 </div>
			 <div class="aling-bottom d-inline-block">
				 <label for="fecha_max">Hasta</label>
				 {{ filtro_form.hasta }}
				 {{ filtro_form.hasta.errors }}
			 </div>
            {% include "sh/filtro_form.html" %}
        </form>
        <br>
        <div class="table-responsive">
            <table class="table table-striped table-sm">
                <thead>
                    <tr>
                        <th>Inicio</th>
                        <th>Fin</th>
                        <th>Comando</th>
                        <th>Usuario</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    
                    {% for obj in list.object_list %}
                    <tr>
                        <td><a href="{% url 'sh:command' obj.pk %}">{{ obj.start|date:"d/m/Y H:i:s" }}</a></td>
                        <td><a href="{% url 'sh:command' obj.pk %}">{{ obj.end|date:"d/m/Y H:i:s" }}</a></td>
                        <td><a href="{% url 'sh:command' obj.pk %}">{{ obj.text|truncatechars:100 }}</a></td>
                        <td><a href="{% url 'sh:command' obj.pk %}">{{ obj.user|default:"" }}</a></td>
                        <td class="text-right">
                            <a href="{% url 'sh:save_command' obj.pk %}" class="btn btn-sm">Guardar en favoritos</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% include 'sh/paginado.html' %}
        </div>
    </div>
</div>
{% endblock %}

sh/templates/sh/fecha.html
<style>
.{{ attrs.name }}_anterior_widget{
	display: block;
	padding-top: 5px;
	margin-top: 8px;
	border-top: 1px solid #eee;
}
</style>
{% if form.instance.id %}
<div class="form-group">
	<label for="">{{ widget.label|default:attrs.name }}</label>
	<input type="{{ widget.input_type }}"
		{% if widget.is_required %}
			required="required"
		{% endif %}
		{% for k, v in attrs.items %}
			{{ k }}="{{ v }}"
		{% endfor %}
	>
</div>
{% else %}
<div class="custom-widget-wrapper">
	<label class="control control-checkbox">
		<input type="checkbox" name="usar_{{ attrs.name }}_anterior" id="id_usar_{{ attrs.name }}_anterior" />
			Usar {{ widget.label|default:attrs.name|lower }} anterior
		<span class="control_indicator"></span>
	</label>

	<div class="form-group {{ attrs.name }}_anterior_widget" id="id_{{ attrs.name }}_anterior_widget" style="display:none">
		<label for="">{{ widget.label|default:attrs.name }}</label>
		<input type="{{ widget.input_type }}"
			{% if widget.is_required %}
				required="required"
			{% endif %}
			{% for k, v in attrs.items %}
				{{ k }}="{{ v }}"
			{% endfor %}
		>
	</div>
</div>
{% endif %}


<script>
$(function(){
	$("#id_usar_{{ attrs.name }}_anterior").change(function(){
		if ($(this).is(':checked')) {
			$("#id_{{ attrs.name }}_anterior_widget").show();
		} else {
			$("#id_{{ attrs.name }}_anterior_widget").hide();
		}
	});
});
</script>

sh/templates/sh/filtro_form.html
<div class="align-bottom d-inline-block">
	Buscar:
	{{ filtro_form.q }} 
	{{ filtro_form.q.errors }}
</div>
<div class="align-bottom d-inline-block">
	Elem pag:
	{{ filtro_form.page_size }} 
	{{ filtro_form.page_size.errors }}
</div>
<div class="align-bottom d-inline-block">
	<input id="btnBuscar" type="submit" value="Buscar" class="btn btn-primary">
	{% if request.GET.f %}
		<a href="{{ request.path }}" id="btnCerrar" class="btn btn-danger"><i class="icon ion-md-close"></i></a>
	{% endif %}
	<input type="hidden" value="1" name="f" />
</div>

{% if exportar_excel or exportar_pdf %}
<div class="align-bottom d-inline-block filtro_exportar">
	<div id="btnClassMenu" class="btn-group" role="group">
    
    <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="icon ion-md-cloud-download"></i>
    </button>
	

    <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
    	{% if exportar_excel %}
      	<a class="dropdown-item" href="#" data-tipo="excel">Excel</a>
      	{% endif %}

      	{% if exportar_pdf %}
      	<a class="dropdown-item" href="#" data-tipo="pdf">PDF</a>
      	{% endif %}

    </div>
  </div>
</div>
{% endif %}

sh/templates/sh/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="es" class="clean-layout">
<head>
    <meta charset="UTF-8">
    <title>{{ title|default:'Django Sh' }}</title>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="icon" href="https://admintotal.com/site_media_central/favicon.png" type="image/png" />
    <link href="https://unpkg.com/ionicons@4.5.9-1/dist/css/ionicons.min.css" rel="stylesheet">

    
    <link href="//fonts.googleapis.com/css?family=Lato:100,300,400,700,900" rel="stylesheet"> 
    <link rel="stylesheet" href="{% static 'sh/js/jquery-ui-1.13.1/jquery-ui.min.css' %}">
    <link rel="stylesheet" href="{% static 'sh/js/bootstrap-5.1.3/css/bootstrap.css' %}">   

    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>


    <script type="text/javascript" src="{% static 'sh/js/bootstrap-5.1.3/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'sh/js/jquery-ui-1.13.1/jquery-ui.js' %}"></script>
    <script type="text/javascript" src="{% static 'sh/js/datetimepicker/jquery-ui-timepicker-addon.js' %}"></script>

    <style>
    html, body{
        background-color: #1e1f1b;
        color: #b5b5b5;
    }
    .table,
    .table a{
        color: #b5b5b5;
    }
    .table td, 
    .table th {
        border-color: rgba(255,255,255,.2) !important;
    }
    .CodeMirror{
        font-size: .95em;
        position: relative;
        height: auto;
    }
    .top-filters{
        background-color: #fff;
        box-shadow: 0 1px 2px rgba(0, 0, 0, 0.25);
        position: relative;
        z-index: 0;
    }
    .texto_respuesta {
        opacity: .8;
        font-size: .9em;
    }
    </style>
    {% block extra_head %}
    {% endblock extra_head %}
</head>
<body>
    <div class="container-fluid">
        <div class="d-flex flex-wrap justify-content-between align-items-center py-2">
            <div>
                <a href="{% url "sh:command" %}" class="btn btn-sm btn-link mr-2 text-light font-weight-bold"> 
                    Django sh
                </a>
            </div>

            <div>
                <a href="{% url "sh:command" %}" class="btn btn-sm btn-dark mr-2">
                    Nuevo comando
                </a>
                <a href="{% url "sh:command_history" %}" class="btn btn-sm btn-dark mr-2">
                    Historial de comandos
                </a>
                <a href="{% url "sh:saved_commands" %}" class="btn btn-sm btn-dark mr-2">
                    Comandos guardados
                </a>
                <a href="{% url "sh:settings" %}" class="btn btn-sm btn-dark mr-2">
                    Configuración
                </a>
                <a href="{% url "sh:reports" %}" class="btn btn-sm btn-dark mr-2">
                    Reportes
                </a>
            </div>
        </div>
        {% block contenido %}
        {% endblock contenido %}
    </div>

    {% block js %}
    {% endblock js %}
</body>
<script>


    
jQuery().ready(function () {

    var calendar_options = {
    changeMonth: true,
    yearRange: "-30:+1",
    changeYear: true,
    dateFormat: 'dd/mm/yy',
    buttonImageOnly: true
    };

    var cal_options_h = {
        hourMin: 0,
        hourMax: 23,
        dateFormat: 'dd/mm/yy',
    };

    $(".has_datepicker").datepicker(calendar_options); 
    $(".has_datetimepicker").datetimepicker(cal_options_h); 


});
            
</script>
</html>